version: '3'
services:
  db:
    image: mongo
    restart: always
    container_name: mongo-sky-react-chat
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwer1234
      - MONGO_INITDB_DATABASE=mongo-sky-react-chat
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
